import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@heroui/toast";
import { HeroUIProvider } from "@heroui/system";
import ReactQuery from "@/providers/ReactQuery";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Cop vs Criminal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <ReactQuery>
          <ToastProvider />
          <main className="dark text-foreground bg-background">
            <HeroUIProvider>{children}</HeroUIProvider>
          </main>
        </ReactQuery>
      </body>
    </html>
  );
}
